### PR TITLE
Git hooks and CI checks for aiken.lock and plutus.json

### PR DESCRIPTION
**Pull request by GeorgeFlerovsky**
## CI check for `aiken.toml` and `plutus.json`

The CI checks that, after running `aiken build`, the `aiken.lock` and `plutus.json` files are the same as the ones committed in the PR branch.

## Git hooks

A new `.githooks` folder contains the project's standardized git hooks, which all contributors should enable on their machines.

To enable the git hooks, run `make enable-git-hooks`.

To disable the git hooks, run `make disable-git-hooks`.

### CODE REVIEW

**Review by solidsnakedev — APPROVED** [review]

**Comment by keyan-m** [comment]
While these are good practices, this repo is a package and its `plutus.json` has no value. @GeorgeFlerovsky what is the rationale here?

**Comment by GeorgeFlerovsky** [comment]
> While these are good practices, this repo is a package and its `plutus.json` has no value. @GeorgeFlerovsky what is the rationale here?

Why doesn't it have value?

**Comment by keyan-m** [comment]
All the validators here are just examples.

**Comment by GeorgeFlerovsky** [comment]
> All the validators here are just examples.

I see. So you're saying only the `lib` folder matters in this repo, not the `validator` folder.

OK, I guess that's a good argument to stop tracking `plutus.json` here.

(But we still must track `aiken.lock`)

**Pull request merged**
